-- core configurations
require("user.core.options")
require("user.plugins")
require("user.core.keymaps")

require("user.colorschemes")
require("user.keymaps")
require("user.treesitter")
require("user.telescope")
require("user.lualine")
require("user.signify")
require("user.cmp")
require("user.autopairs")
require("user.lsp")
require("user.trouble")
require("user.bufferline")
require("user.nvimtree")
require("user.comment")
require("user.autocommands")
require("user.snippets")
